### ISSUE TITLE
drop maquette

### ISSUE THREAD

**Issue by johannestroeger** [soyuka/dpicker#1]
let users decide which lib to use

**Comment by soyuka** [comment]
Maquettejs is ~3kb, not heavy for a virtual dom library. It helps to keep the code light and clean, removing the dependency will add a lot of code to handle events and binding.

**Comment by johannestroeger** [comment]
totally understand this! sorry for beeing not so concrete, i should rewrite the topic as it is a bit offensive and wrong.

so what about requiring `h` as opt-in: 

```
const DatePicker = require('dpicker')
const datePicker = new DPicker({ h: require('my-own-dom-lib') })
```

this way you could still fallback to `maquettejs` if `h` isNil. what do you think about this approach?

**Comment by soyuka** [comment]
Interesting, but what other libraries are compatible with this VNode scheme? I'm also using the maquettejs projector [here](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L183), [here](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L197) and on setters [here](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L671). What would be the alternative for those?

**Comment by soyuka** [comment]
Virtual dom libraries that could replace maquettejs:
http://mithril.js.org/
reactDOM

Maybe others? I need to test those but it might get complicated to handle each use case (like react.render / react createlement or `m.mount` for mithril instead of the maquettejs projector.

**Comment by soyuka** [comment]
https://github.com/soyuka/dpicker#custom-hyperscript-library
