### ISSUE TITLE
hideOnDayClick = false doesn't work anymore

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#10]
it always closes after clicking the day.

**Comment by soyuka** [comment]
Just tested this on the demo:

```
;[].slice.call(document.querySelectorAll('input[type="date"],input[type="datetime"]')).forEach(e => new DPicker(e, {hideOnDayClick: false}));
```

Works fine. Please init this option on date picker creation I don't want to add a getter/setter for this ;).

**Comment by stereonom** [comment]
ah, didn't know I can init it like this.
