### ISSUE TITLE
min and sameDay

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#11]
I set `min = moment()` and let's say it’s `15:40` I get these options for `hour`: `15`, `16`, `17`… `23`.
But when I choose `16`and reopen the `select` the option `15` disappeared. Selecting `17`disables `15`and `16`…

**Comment by soyuka** [comment]
@stereonom can you try those last fixed issues from the master branch (#8 #9) and let me know?
Thanks!

I'm releasing new major if everything looks good. Major change is `dpicker.isEmpty` => `dpicker.empty`

**Comment by stereonom** [comment]
i checked out the master, run `npm install` and `bower install` than `gulp` but it fails with `SyntaxError: Use of const in strict mode.`
any idea how I can get the master to run?

**Comment by soyuka** [comment]
Hmm, node version?

**Comment by soyuka** [comment]
Btw you should only need:

```
npm install
gulp
```

[see travis.yml](https://github.com/soyuka/dpicker/blob/master/.travis.yml#L10). It runs fine on node 4 and node 6.

**Comment by stereonom** [comment]
yeah, node version. :-) works with node 4.

#9 is fixed.
#8 and #11 are still the same.

Here's how I init the picker:

``` js
var mypicker = new DPicker(document.getElementById("quickdate"), {
		hideOnDayClick: false,
		hideOnDayClick: false,
		min: moment(),
		model: moment(),
		time: true,
		meridiem: false,
		onChange: adjustDates,
		format: 'DD.MM.YYYY HH:mm',
		step: 15
	});
```

**Comment by soyuka** [comment]
This does not happen to me (no tools to do a gif :cry: ) are you sure you ran gulp?

**Comment by stereonom** [comment]
yeah. would you send me your current version to philip@stereonom.de ? I give that a try

**Comment by soyuka** [comment]
Interesting, this is related to the `value=""` attribute. I must investigate further.

**Comment by stereonom** [comment]
removed the value, used  `v2.0.1`and still this is happening:
![asd](https://cloud.githubusercontent.com/assets/883533/17166659/aab6dadc-53d8-11e6-8b86-82d72d27d082.gif)

**Comment by soyuka** [comment]
But now hours selection is alright?

> When min is after 45

You mean the min date minutes or the model ones?

**Comment by stereonom** [comment]
The hour selection is one hour to low as you can see in the image.
`min = 15:53` with `step = 15` shouldn't give me the option for `15`in the hour select and all 4 options in the `minute` select field
