### ISSUE TITLE
Rounding with steps

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#16]
I think you're rounding wrong with steps:
Example #1: `min=03/08/2016 14:37`, `min=03/08/2016 14:37`, `step=15`
Value in the Picker: `03/08/2016 14:30`, but in the `minute` selector the only option is `45`.

Example #2: `min=03/08/2016 14:38`, `min=03/08/2016 14:38`, `step=15`
Value in the Picker: `03/08/2016 14:45`. correct.

![image](https://cloud.githubusercontent.com/assets/883533/17212895/f8fccc66-54d1-11e6-9ec5-bb54034112d4.png)

**Comment by soyuka** [comment]
It takes the closest one, it should be the closest available, let me look into it.
