### ISSUE TITLE
flickering select field in chrome and opera. browser bug?

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#17]
When I open the select-field it disappears for a short moment.
This happens in Chrome 52 and Opera 38.
It's not happening  in Safari 9.1.1 and FireFox 47, so perhaps just a browser-bug?

![juli-28-2016 15-49-32](https://cloud.githubusercontent.com/assets/883533/17214817/f65bb432-54da-11e6-8f17-228e20af4f23.gif)

**Comment by soyuka** [comment]
Indeed I observed the same, I'll dig into this!

**Comment by soyuka** [comment]
Can't reproduce anymore :\

**Comment by stereonom** [comment]
:-/
I get it with the `3.0.4` demo.

**Comment by soyuka** [comment]
It's too fast in my browser, but I know why this happens, just don't know the why of the why ;)

**Comment by soyuka** [comment]
Can't stopPropagation with maquettejs so I removed the blur event from hyperscript and put it in a native `addEventListener`. 

Now, it doesn't render time on input blur ;).
