### ISSUE TITLE
Customizable DOM ordering

### ISSUE THREAD

**Issue by florianpircher** [soyuka/dpicker#18]
For internationalizations sake, making the order of input elements customizable would be a great feature. Some cultures notate the year before the month, some the month before the year. Sometimes selecting a time is more important than selecting the date, so the time-input-fields should appear on top of the picker. One possible way of implementing this feature is by specifying the order at creation time, like:

```javascript
var dp = new DPicker(container, {
  model: moment(),
  order: ['time', 'month', 'year'], // or ['H', 'i', 'm', 'Y']
  // ...
```

**Comment by florianpircher** [comment]
Thank you!

**Comment by soyuka** [comment]
You're welcome. It gives the ability to skip parts too. For example `['days']` will only render days. I didn't expand this to time because hours always gets before minutes but let me know if the feature is needed.

**Comment by florianpircher** [comment]
Great, congratulations to 100 stars!
