### ISSUE TITLE
Add month navigation with directional arrows

### ISSUE THREAD

**Issue by florianpircher** [soyuka/dpicker#19]
A picker without a year field (e.g. `order: ['time', 'months', 'days']`) would profit from an arrow navigation for selecting the next/previous month. This would allow pickers used for short-term selections (e.g. max next 3 months), which don’t need a year field, to still jump to the next year.

I made a quick mockup:

<img width="372" alt="2016-08-03 at 16 10 28" src="https://cloud.githubusercontent.com/assets/3776198/17368674/5935617a-5995-11e6-8b2a-48953ff4fcee.png">

**Comment by soyuka** [comment]
Interesting idea. You can implement this yourself in a module !

For example (file `dpicker.date-navigation.js`):

```
const renderPreviousMonth = DPicker.injector(function renderPreviousMonth(events, data, toRender) {
  return DPicker.h('button', { onclick: events.previousMonth }) //add some appropriate attributes
})

const renderNextMonth = DPicker.injector(function renderNextMonth(events, data, toRender) {
  return DPicker.h('button', { onclick: events.nextMonth })
})

const dateNavigation = DPicker.modules.dateNavigation = {
  render: {
    previousMonth: renderPreviousMonth,
    nextMonth: renderNextMonth
  },
  events: {
    previousMonth: function previousMonth() {
       this._data.model.add(1, 'month')
    },
    nextMonth: function nextMonth(evt) {
       this._data.model.add(-1, 'month')
    }
  }
}
```

Then, just order your rendered functions through the `order` parameter :D.

Thought to myself: I should try to find a neat solution for #1 which would enable to add custom dom elements to the rendered ones easily. This would however be a penalty if you just want to use dpicker seamlessly (without having to inject your own hyperscript library).

**Comment by florianpircher** [comment]
Wow! I’ve looked at the custom modules docs before, but this clears things up a lot. I think, this code would provide a nice example implementation for the docs, as the other modules (e.g. dpicker.arrow-navigation) are quite long and for someone without much knowledge of the codebase difficult to read.

**Comment by soyuka** [comment]
Thought the same as I was writing it ^^. Added.
