### ISSUE TITLE
Touch friendly behavior

### ISSUE THREAD

**Issue by florianpircher** [soyuka/dpicker#20]
DPicker can be closed by clicking outside of the picker. This doesn’t work when touching outside of the picker. I tried implementing this by adding

```javascript
document.addEventListener('touchend', this._events.hide);
```

after [line 144 in dpicker.js](https://github.com/soyuka/dpicker/blob/development/src/dpicker.js#L144). This does work, the only problem is, that the date/datetime input field is still focused after closing the picker, so all mobile OS are still showing the virtual keyboard.

**Comment by soyuka** [comment]
Use [`document.getElementById(this.inputId).blur()`](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L507).

**Comment by soyuka** [comment]
Want to pull-request on this or should I do it? I think this has to go in core.

**Comment by soyuka** [comment]
```diff
index 022187e..85e4043 100644
--- a/src/dpicker.js
+++ b/src/dpicker.js
@@ -176,7 +176,13 @@ function DPicker(element, options = {}) {
   element.setAttribute('id', this._container)
   element.addEventListener('keydown', this._events.keyDown)

-  element.querySelector('input').addEventListener('blur', this._events.inputBlur)
+  let input = element.querySelector('input')
+
+  input.addEventListener('blur', this._events.inputBlur)
+  document.addEventListener('touchend', function() {
+    input.blur()
+  })
+
   return this
 }
```
