### ISSUE TITLE
Dpicker Does Not Work on Safari 9.1.3

### ISSUE THREAD

**Issue by fatihturan** [soyuka/dpicker#23]
Hi,

Dpicker does not work on Safari. There are an error in console: http://jmp.sh/9pg9xgl

Best regards.

**Comment by joeinnes** [comment]
Safari doesn't support arrow functions. The code itself works, it's just the oneliner to initialise that doesn't yet.

Use this instead:
`[].slice.call(document.querySelectorAll('input[type="date"],input[type="datetime"]')).forEach(function(e){new DPicker(e);});`
