### ISSUE TITLE
v4.0.0

### ISSUE THREAD

**Issue by soyuka** [soyuka/dpicker#26]
I just dropped maquettejs or any related hypescript library. It was a pain trying to be compatible with every one of them because they don't follow the same behavior. 

For example:
- Maquettejs props takes `classes` which is an object with booleans
- Inferno uses `className`
- Mithril uses `class`

This also allows cleaner DOM update where it updates only the parts we need to update.

Tests have not been modified, every previous feature should still be available. The only thing that changed is the behavior of an invalid input. Previously it was changing the date to the closest available. We now just leave the input invalid.

For more informations about changes: https://github.com/soyuka/dpicker/blob/master/CHANGELOG.md#400

ping @florianpircher @stereonom it would be lovely if you have time to update and tell me if something broke.

**Comment by stereonom** [comment]
`4.0.0` Wow. Great work – keep the updates coming because:
> new is always better — Barney Stinson


I'm currently using DPicker with backbone/require.js.
I kicked maquette out, updated to `4.0.0` and boom: it broke.

I think the problem is as follows:
The `input`-element isn't in the DOM when I try to initialize DPicker. It's just a jQuery-Object in a variable (`new DPicker($myInput.get(0), {…})`). This wasn't an issue before.

I can work around that new behaviour if there is no other way.

**Comment by soyuka** [comment]
Interesting, how can I reproduce this with vanillajs?

I tried here without success: https://jsfiddle.net/qfkp8p6j/ don't hesitate to add jquery! 

Thanks for those feedbacks, and there should be no issues with the migration what so ever so this is a bug IMO :yum:.

**Comment by stereonom** [comment]
Here we go: https://jsfiddle.net/qfkp8p6j/1/

**Comment by soyuka** [comment]
Ok I bumped a fix that takes the first element. There's still an issue because the input parent node is a DocumentFragment and therefore can not have classes (the previous fiddles will break [here](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L147)). 

https://jsfiddle.net/qfkp8p6j/3/ this does work now :).

**Comment by stereonom** [comment]
I found another bug.
https://jsfiddle.net/qfkp8p6j/4/

When I use a german moment, sunday isn't the first day and in line [970](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L970) it fails, because `children[i]`is undefined.

**Comment by soyuka** [comment]
Nice catch.
