### ISSUE TITLE
Clicking on day doesn't update days (active button)

### ISSUE THREAD

**Issue by oncode** [soyuka/dpicker#27]
When I click on a day, the input field gets updated/redrawn correctly, but in the table, the old day is still active. Shouldn't the `dayClick` event also redraw the days?

Line 420 of src/dpicker.js:
```
this.redraw(['input'])
```

to:
```
this.redraw(['input', 'days'])
```

**Comment by soyuka** [comment]
Thanks!

**Comment by soyuka** [comment]
Published in 4.0.6

**Comment by oncode** [comment]
Hell that was fast, thank you, also for the awesome library!
