### ISSUE TITLE
iOS: can't change time or month

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#28]
Hi.

When I try to change the time or the month and tab on these `select` fields the main `input`-element gets focused and the normal qwertz-keyboard shows up.

I tried to make this `input` readonly, than no keyboard appears – doesn't help.

Any chance you can fix this?

(This happens under iOS10)

**Comment by soyuka** [comment]
On iOS I'm not able to trigger the dpicker but if you've a `type="date"` it looks like it falls back to the iPhone UI. Maybe there's something to do here to map the date to a correct date, not sure.

Could you give me the code that reproduces this particular issue?

**Comment by stereonom** [comment]
sure.
here u go:

https://jsfiddle.net/qfkp8p6j/5/

**Comment by soyuka** [comment]
Okay I get it now, when you touch the select it fails. On it.

**Comment by stereonom** [comment]
yepp, exactly.
sorry for describing it so wired.

**Comment by soyuka** [comment]
This is harder then I thought, I'll need to debug this from my mac with the developer tools. I can't find why it's focusing on the input with `alert()` ^^.

**Comment by stereonom** [comment]
I also tried it with `alert()` to give u a hint. But haven't found a starting point. ;-)

**Comment by soyuka** [comment]
Okay, after debugging for 30 minutes I couldn't figure it out, until I saw the html:

```
<label><input type="datetime" name="mydatetime" autocomplete="off" step="30"></label>
```

Because of the `<label>` Safari auto focuses the input on iPhone.

**Comment by stereonom** [comment]
![d'oh](https://media.giphy.com/media/6GLO7aJ98f2Ao/giphy.gif)

I'm so sorry.

**Comment by stereonom** [comment]
perhaps you should change your demo now as well – there is a `label` wrapping everything as well :-)

**Comment by soyuka** [comment]
:+1: No Problem!
