### ISSUE TITLE
Fallback to native pickers

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#29]
Hi.
When setting `type="datetime"` on the inital `<input>` the android-browser think he's clever and prompts the user with its native controlls for `datetime`. (iOS does the same with `type="date"`)

The problem with dpicker not showing up is that `steps`, `min` & `max` have no influence on the native-OS-pickers.

I tried to work around with `type="text"`:
- iOS doesn't show the `selects` for time
- android offers me a qwertz-keyboard so I can type anything – no dpicker at all.
So this doesn't help.

Perhaps a solution would be to get rid of this `input`? (the downside would be that no manual input would be possible, but that would be ok, or is a setting)

**Comment by soyuka** [comment]
It should work with the `type="text"`. I can check out how native pickers are handling steps or things like this, because it would be IMO the best option (use native when available).

**Comment by stereonom** [comment]
I agree that native pickers would be better, **IF** they support `steps`, `min` & `max` which I for iOS doesn't look to good: http://caniuse.com/#feat=input-datetime

**Comment by stereonom** [comment]
I tried `min`, `max`, `step` on a Samsung S6, Moto G (3rd), Nexus 5.
All these support `min` and `max`, but I can't get `step` to work.

iPhone doesn't support anything 👎

**Comment by stereonom** [comment]
Ok.
It seems the "best" solution for now to init `DPicker` on a `div` not on an `input`.

```
var DPicker = new DPicker(v.$el.find('.picker__container'), {
	hideOnDayClick: false,
	display: true,
	min: v.options.min || undefined,
	max: v.options.max || undefined,
	model: v.model,
	onChange: v.change,
	time: true,
	step: v.options.step || 60,
	format: 'DD.MM.YYYY HH:mm',
	order: ['time', 'months', 'days'],
	days: moment.weekdaysMin()
});

```

To prevent iOS and Android to show the normal keyboard I added

```
$.find('.dpicker > input').on('focus', function() {
	$.find('.dpicker > input').blur();
});
```

**Comment by soyuka** [comment]
I'm not sure there's much I can do here. I don't want to prevent the native support if any possible for accessibility reasons. Feel free to tweak what you can or ask if you want some particular implementation.
