### ISSUE TITLE
time selector

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#30]
Hi.

Is it possible to get the `select`for the time as one `select` instead of two?
When using `step=30` the two `select`s aren't very useful.

**Comment by soyuka** [comment]
For this you need to build an extension, I've a plane to catch but I'll get back to you soon.

**Comment by stereonom** [comment]
awesome!

**Comment by stereonom** [comment]
Here's a bug:

![image](https://cloud.githubusercontent.com/assets/883533/23603643/3f90de2e-0256-11e7-9d0f-5ef13ccef0a4.png)

The order isn't correct.

**Comment by soyuka** [comment]
Fixed in 4.0.10
