### ISSUE TITLE
IE11 & 10: DPicker not loading

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#31]
![image](https://cloud.githubusercontent.com/assets/883533/23122977/d21d9728-f766-11e6-9543-f7ecd6b42f2f.png)
Something is broken in IE11 & IE10.

Edge ist fine.

**Comment by soyuka** [comment]
May you try 4.0.7 by including `dpicker.polyfills.js`?

**Comment by stereonom** [comment]
`4.0.7` works in IE11 & 10. Thanks :heart_eyes:
