### ISSUE TITLE
make days in next month selectable

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#32]
![image](https://cloud.githubusercontent.com/assets/883533/23396477/510b50f6-fd94-11e6-81ee-8bd7f03cb960.png)

Hi.
Because I can't select the days of the next month it seems that when its the last day of the month the user can't select anything else.
Is there a way to make these days of the next month clickable, so the problem disappears? :-)

Thanks!

**Comment by soyuka** [comment]
Can't you allow to change the month? Or, you could change the selected month when date == lastDayOfMonth?

It's not really intended and hard to implement because it'd need to know that those are days for the next month, and if the model month changes, it'll refresh the calendar.

**Comment by stereonom** [comment]
The user is allowed to change the month – but I think it isn't obvious he/she can, because the days of march aren't clickable.

I can't `date == lastDayOfMonth` because the selected day (28.02) is a valid day.

I haven't ask u if it was easy to do 👍

**Comment by stereonom** [comment]
Wow. Thanks!

Here are some bugs:

1. days of next month aren't clickable on month where "min" has to be respected.

![image](https://cloud.githubusercontent.com/assets/883533/23603809/dfc7bd7c-0256-11e7-8945-60295cbb60fe.png)
(min = now)

2. When selecting a day which is selectable in current AND next/prev month both those days are active
![image](https://cloud.githubusercontent.com/assets/883533/23604057/d1c7790a-0257-11e7-91ce-fb2c5dd2b466.png)
![image](https://cloud.githubusercontent.com/assets/883533/23604069/db668460-0257-11e7-9901-92fcc2e64949.png)

**Comment by soyuka** [comment]
whoops, sorry doing many things at once.

Patched in 4.0.11

**Comment by stereonom** [comment]
:-) no problem.

I'm good at finding bugs.

Here's another one in `4.0.11`

![image](https://cloud.githubusercontent.com/assets/883533/23605290/4e28999e-025c-11e7-93ca-2a0f7a248238.png)

`min` isn't respected in daysOfPrevMonth

**Comment by soyuka** [comment]
Not sure I understood the last case give me min, max, model(s) please

**Comment by stereonom** [comment]
![image](https://cloud.githubusercontent.com/assets/883533/23605623/b8f50662-025d-11e7-9f9d-0b90b29742a3.png)
min = 29.08.2017
max = 07.09.2017 (but that's not the problem)

**Comment by soyuka** [comment]
![dpicker-ok](https://cloud.githubusercontent.com/assets/1321971/23606404/d8b4ed48-0260-11e7-9e0e-db1639057d75.png)

looks fine to me?

**Comment by stereonom** [comment]
why isn't 30 and 31.08 not selectable?

**Comment by stereonom** [comment]
![image](https://cloud.githubusercontent.com/assets/883533/23606557/8b775920-0261-11e7-988e-d61ae9dd55c0.png)

**Comment by soyuka** [comment]
Can you try 4.0.12? Thx!

**Comment by stereonom** [comment]
👍  it works.
