### ISSUE TITLE
5.0.0 - Breaking things :D (not released yet)

### ISSUE THREAD

**Issue by soyuka** [soyuka/dpicker#33]
Recently I was thinking in how I could speed up the rendering of DPicker. I ended up feeling that the whole `vdom` part I initially implemented (first through maquette, then by adding an improvised `h` function) was too much. I also happen to discover `bel` and `nanomorph` which are both really fast and well-optimized. 

Therefore, I implemented them in the `development` branch to see how it goes, and it goes well :D. Thanks to the `yo-yoify` package, the DOM elements are bundled and we even don't need `bel` as a dependency in the `dist` files (it basically transforms bel`<foo>` in `document.createElement('foo')`).
The drawback of this is that it will slightly increase dpicker size (because of the `yo-yoify` process). IMO the size increase is irrelevant compared to the performance improvement.

For now I'm waiting for https://github.com/yoshuawuyts/nanomorph/pull/54 to be merged or this is a no-go :|. Currently the `development` branch uses my fork and tests are all green. The only breaking thing is that `DPicker.h` has been removed, therefore old DPicker modules will break.

@florianpircher  please let me know if you still use #19! It'll totally break if you wanted to upgrade and I'm considering adding it to the dpicker modules :).

ping @stereonom @thcolin  

References: 
- [nanomorph](https://github.com/yoshuawuyts/nanomorph)
- [bel](https://github.com/shama/bel)

**Comment by florianpircher** [comment]
Yes, #19 is still in use. Another module that I have developed adds a close button/confirm to the picker.

```javascript
DPicker.modules.closeButton = {
  render: {
    closeButton: function renderCloseButton(events, data, toRender) {
      const properties = {
        class: 'dpicker-close-button',
        type: 'button',
        onclick: events.hidePicker
      }
      return DPicker.h('button', properties, 'Confirm')
    }
  },
  events: {
    hidePicker: function hidePicker() {
      this.display = false
    }
  }
}
```

<img width="366" alt="bildschirmfoto 2017-03-31 um 16 50 59" src="https://cloud.githubusercontent.com/assets/3776198/24555652/43759792-1632-11e7-8368-7f1bda47304b.png">

I wish you success with your 5.0.0 release! 🎊📅🎉

**Comment by soyuka** [comment]
Nice, what are you using to bundle things? Btw your calendar is pretty <3.

I'll try to find a way to make those modules work with `5.0.0` but it'll require some changes :). Anyway it'll be a major release and I won't break things in `4.x`!

**Comment by florianpircher** [comment]
I use npm to install moment and DPicker. DPicker is configures in a dpicker-init.js and all JavaScript files are concatenated and minified using gulp.

**Comment by soyuka** [comment]
Interesting, would it help to have a file that adds up `dpicker.time.js` and `dpicker.js` (or any other)? I assume you require them both independently? I may review this whole part because currently we need a `DPicker` global variable and globals are evil \o/.

Thanks for your input, greatly appreciated :).

**Comment by florianpircher** [comment]
Currently I am concatenating moment.js, dpicker.js and dpicker.time.js. Combining the picker and the time module, e.g. dpicker+time.js, would still require a concatenation build process for including moment.js and the DPicker-init file, so I don’t think bundling DPicker core with its modules would make a big difference to my workflow.

**Comment by soyuka** [comment]
The following should work for next version :). Releasing a beta tonight.

```
DPicker._renders.closeButton = function renderCloseButton(events, data) {
  const button = document.createElement('button')
  button.innerText = 'Confirm'
  button.type = 'button'
  button.classList.add('dpicker-close-button')
  button.addEventListener('click', events.hidePicker)
  return button
}

DPicker._events.hidePicker = function hidePicker() {
  this.display = false
}
```

I've added the previous/next month plugin to the code, added some conditions for min/max.

If you want to use the next version you may include `dist/dpicker.navigation.js` plugin instead of #19.

**Comment by florianpircher** [comment]
Looks great! Before using DPicker I’ve never used any hyperscript library, therefore the use of vanilla JavaScript DOM objects looks comforting.

Why are `_renders` and `_events` prefixed with an underscore? It fees to me like both of them are „public“ and should be modified by the developer. This way it looks kind of _hacky_, almost as if I would change some parts of DPicker that should not be changed.

**Comment by soyuka** [comment]
Yeah your right! Thanks!
