### ISSUE TITLE
undefined state when changing year

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#38]
Hi.

I used your demo to reproduce this bug:
set 'min' to '1. August 2017'
set 'max' to '1. February 2018'

(It works with everything smaller than a year in advance)

Now try to set year to `2018`.
The displayed date is now `1. August 2018` which is incorrect, as it is forbidden by `max`
The month I can choose dates from is January, but I can't select anything.

![image](https://user-images.githubusercontent.com/883533/28823477-0e65b950-76be-11e7-951a-6057ee9755c7.png)

**Comment by soyuka** [comment]
nice one thanks, fixed in #38 (added a month change on the model when not in the min/max interval).
