### ISSUE TITLE
ReferenceError: Can't find variable: assert

### ISSUE THREAD

**Issue by florianpircher** [soyuka/dpicker#41]
Using dpicker.min.js at version 5.0.8, the picker can not be opened. Instead, when clicking on the input field the following error is displayed in the JavaScript console:

```
ReferenceError: Can't find variable: assert
```

<img width="499" alt src="https://user-images.githubusercontent.com/3776198/31124783-314e4cd4-a846-11e7-95fd-d3d748f5a7be.png">

I managed to bypass this error be defining a global `assert` object:

```js
window.assert = { equal: () => {} }
```

**Comment by soyuka** [comment]
`unassertify` should take care of this :|
