### ISSUE TITLE
5.1.0: dpicker gone.

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#43]
Hi.

My Picker is gone.
I set `display: true` while initialising dpicker, but nothing get rendered (only the `input`)

![image](https://user-images.githubusercontent.com/883533/34726931-b784801e-f555-11e7-9496-fe011dd009c1.png)

**Comment by stereonom** [comment]
I added some logging.
It gets initialised with `display: true` but after clicking on sth hide() gets triggered.

**Comment by stereonom** [comment]
Ha!
I found it:
I need to set `hideOnOutsideClick: false` and now it's working again

**Comment by soyuka** [comment]
Hey! Indeed I made a performance change where I don't compute the calendar if `display: false`. I've assumed (maybe wrongly) that it wouldn't break anything. Lmk if you have any issues!

**Comment by stereonom** [comment]
Perhaps the docs are a little bit misleading. 
I thought `display: true` means show it no matter what. 
I only came up with `hideOnOutsideClick` having something to do with my problem after reading the source. 

You could add a description to the `display` option to make that clear.

**Comment by stereonom** [comment]
On mobile (with touch) the picker was still hidden sometimes, while on chrome e.g. everything worked fine.
So I put an `alert` on all `display = false` in the code.
I found, that the `blur` event is fired.

The problem seems to be that your assumption that every `touchend` is an `blur` is wrong:
```
document.addEventListener('touchend', function (e) {
        _this.events.inputBlur(e);
});
```

So, when I touch the dpicker, it gets hidden.
I haven't come up with a good solution yet, perhaps the check for `hideOnOutsideClick` can prevent this from happening?
And why do you need that listener anyway?

**Comment by soyuka** [comment]
> You could add a description to the display option to make that clear.

Done.

touchend is related to: https://github.com/soyuka/dpicker/issues/20

An attempt to fix this has been done in my last commit.

**Comment by stereonom** [comment]
seems to be fixed. thanks <3
