### ISSUE TITLE
datetime support?

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#6]
Hi.

Any plans for adding support for `<input type="datetime">`?

When you give me a hint, I would try to add it myself.

Thanks!

**Comment by stereonom** [comment]
awesome!

I think you forgot to check for `min`.
I can choose times that are before `min`.

Any chance I can get "steps" for the minute-picker?

**Comment by soyuka** [comment]
Min didn't feel right with time, for example setting:

`min="2014-06-24 22:10:23"` would mean that I could not choose `21:10` even if I choose a posterior date? How would that work for you?

Steps are a great idea for minutes!

**Comment by stereonom** [comment]
with `min="2014-06-24 22:10:23"`you can't choose `21:10` for just that day `2104-06-24`.
When a date in the future is picked all times get available.

**Comment by soyuka** [comment]
Landed in v1.3.6.
